<% def env(a, b); e = ENV["obtvse_#{a}"]; e ? e : b; end %>

title: <%= env :title,     "Timothy Chung's blog" %>
domain: <%= env :domain,   'http://www.timchung.me' %>
name:    <%= env :name,    'Timothy Chung' %>
twitter: <%= env :twitter, 'timchunght' %>
github:  <%= env :github,  'timchunght'  %>
email:   <%= env :email,   'timchunght@gmail.com'  %>
about:   <%= env :about,   'I am a Ruby on Rails Developer and traveller.' %>

# Google Analytics
ga_id:   <%= env :ga,      ''  %>
